schema-version = 1

[package]
title = "inTV Play"
version = "0.1.0"
id = "com.bromteck.appvideo"

[os.version]
min = "1.2"
target = "1.2"

[needs]
[[needs.module]]
id = "/com.amazon.vega.os@IVega_1_2"

[[needs.module]]
id = "/com.amazon.kepler.kepler_media_controls_1@IKeplerMediaControls_0"

[[needs.module]]
id = "/com.amazon.kepler.keplermediadescriptor_1@IKeplermediadescriptor_1"

[[needs.module]]
id = "/com.amazon.kepler.keplerscript_4@IKeplerScript_0"

[[needs.module]]
id = "/com.amazon.kepler.w3cmedia_2@IW3cmedia_3"

[[needs.module]]
id = "/com.amazon.kepler.async_storage__async_storage_2@IAsyncStorage__AsyncStorage_1"

[[needs.module]]
id = "/com.amazon.kepler.gesture_handler_4@IGestureHandler_0"

[[needs.module]]
id = "/com.amazon.kepler.reanimated_4@IReanimated_0"

[[needs.module]]
id = "/com.amazon.kepler.safe_area_context_8@ISafeAreaContext_0"

[[needs.module]]
id = "/com.amazon.kepler.screens_3@IScreens_0"

[[needs.module]]
id = "/com.amazon.kepler.worklets_1@IWorklets_0"

[[needs.module]]
id = "/com.amazon.kepler.navigation__core_8@INavigation__Core_0"

[[needs.module]]
id = "/com.amazon.kepler.navigation__elements_8@INavigation__Elements_0"

[[needs.module]]
id = "/com.amazon.kepler.navigation__native_8@INavigation__Native_0"

[[needs.module]]
id = "/com.amazon.kepler.navigation__routers_8@INavigation__Routers_0"

[[needs.module]]
id = "/com.amazon.kepler.navigation__stack_8@INavigation__Stack_0"

[[needs.module]]
id = "/com.amazon.kepler.linear_gradient_2@ILinearGradient_0"

[components]
[[components.interactive]]
id = "com.bromteck.appvideo.main"
runtime-module = "/com.amazon.kepler.runtime.react_native_kepler_4@IReactNativeKepler_0"
launch-type = "singleton"
categories = ["com.amazon.category.main"]

[wants]
[[wants.service]]
id = "com.amazon.media.server"
[[wants.service]]
id = "com.amazon.mediametrics.service"
[[wants.service]]
id = "com.amazon.media.playersession.service"
[[wants.service]]
id = "com.amazon.mediabuffer.service"
[[wants.service]]
id = "com.amazon.mediatransform.service"
[[wants.service]]
id = "com.amazon.audio.stream"
[[wants.service]]
id = "com.amazon.audio.control"
[[wants.service]]
id = "com.amazon.network.service"
[[wants.service]]
id = "com.amazon.gipc.uuid.*"

# Teclado en pantalla para TextInput.
[[wants.service]]
id = "com.amazon.inputmethod.service"

[offers]
[[offers.service]]
id = "com.amazon.gipc.uuid.*"
